---
- name: Playbook to do the first homework
<<<<<<< HEAD
  hosts: alma
=======
  hosts: alma8
>>>>>>> 19ae9bfd7ee4ff6a6aba4dab0e551e12514f1f7e
  become: yes

  tasks:
    - name: create a user called Ngan
      user:
        name: Ngan

    - name: create file(class6.txt) write in it and give full permission
      lineinfile:
        path: /tmp/class6.txt
        line: "we are learning in classroom 1 or 2"
        mode: a+rwx
        create: yes

    - name: Enable SELinux
<<<<<<< HEAD
      selinux:
        policy: targeted
        state: enforcing
=======
       SELinux:
         policy: targeted
         state: enforcing
>>>>>>> 19ae9bfd7ee4ff6a6aba4dab0e551e12514f1f7e
