all:
  children:
    free_version:
      hosts:
        centos7.class5.com:
        rocky8.class5.com:
    group7:
      hosts:
        centos7.class5.com:
        rhel7.class5.com:
    group8:
      hosts:
        rhel8.class5.com:
        rocky8.class5.com:
    other:
      children:
        centos:
          hosts:
            centos7.class5.com:
        rocky:
          hosts:
            rocky8.class5.com:
            rocky9.class5.com:
        alma:
          hosts:
            alma8.class5.com:
            alma9.class5.com:
        ubuntu:
          hosts:
            ubuntu.class5.com:
    redhat:
      children:
        centos:
          hosts:
            centos7.class5.com:
        rhel:
          hosts:
            rhel7.class5.com:
            rhel8.class5.com:
            rhel9.class5.com:
        rocky:
          hosts:
            rocky8.class5.com:
            rocky9.class5.com:
        alma:
          hosts:
            alma8.class5.com:
            alma9.class5.com:
    ungrouped:
